# Generated by Django 5.2.9 on 2025-12-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('techniciens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_intervention', models.DateField()),
                ('type_intervention', models.CharField(choices=[('installation', 'Installation'), ('reparation', 'Réparation'), ('entretien', 'Entretien')], max_length=20)),
                ('statut', models.CharField(choices=[('terminee', 'Terminée'), ('annulee', 'Annulée'), ('en_cours', 'En cours'), ('prevue', 'Prévue')], default='en_cours', max_length=20)),
                ('panne_constatee', models.TextField(blank=True, null=True)),
                ('pieces_remplacees', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('prix_intervention', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='clients.client')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='clients.fournisseur')),
                ('technicien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='techniciens.technicien')),
            ],
            options={
                'verbose_name': 'Intervention',
                'verbose_name_plural': 'Interventions',
                'ordering': ['-date_intervention'],
            },
        ),
    ]
