# Generated by Django 5.2.9 on 2025-12-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('interventions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='fournisseur',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interventions', to='clients.fournisseur'),
        ),
    ]
