# Generated by Django 5.2.9 on 2025-12-08 14:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0002_alter_intervention_fournisseur'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
