# Generated by Django 5.2.9 on 2025-12-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_intervention_created_at_intervention_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
