# Generated by Django 5.2.9 on 2025-12-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0004_alter_intervention_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intervention',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='updated_at',
        ),
    ]
