# Generated by Django 5.2.9 on 2025-12-10 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_remove_intervention_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='date_creation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='date_modification',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='rappel_envoye',
            field=models.BooleanField(default=False),
        ),
    ]
