# Generated by Django 5.2.9 on 2025-12-10 13:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0006_intervention_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
