# Generated by Django 5.2.9 on 2025-12-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0007_alter_intervention_date_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='date_intervention',
            field=models.DateTimeField(),
        ),
    ]
