# Generated by Django 5.2.9 on 2025-12-16 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0008_alter_intervention_date_intervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='dernier_debut_en_cours',
            field=models.DateTimeField(blank=True, help_text="Dernière fois que le statut est passé à 'En cours'", null=True),
        ),
        migrations.AddField(
            model_name='intervention',
            name='duree_cumulee',
            field=models.DurationField(default=datetime.timedelta, help_text="Durée totale cumulée en statut 'En cours'"),
        ),
        migrations.AddField(
            model_name='intervention',
            name='historique_statuts',
            field=models.JSONField(blank=True, default=list, help_text='Historique des changements de statut avec timestamps'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='temps_en_cours',
            field=models.BooleanField(default=False, help_text="Si l'intervention est actuellement en cours de comptage"),
        ),
    ]
