# Generated by Django 5.2.9 on 2025-12-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_type_installation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='type_installation',
            field=models.CharField(help_text='Format obligatoire: [nombre]KVA. Ex: 5KVA 10KWH 10x550W, 3KVA, 8KVA système hybride, etc.', max_length=100),
        ),
    ]
