# Generated by Django 5.2.9 on 2025-12-17 11:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_email_alter_client_telephone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseur',
            options={'ordering': ['nom'], 'verbose_name': 'Fournisseur', 'verbose_name_plural': 'Fournisseurs'},
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='materiels_fournis',
        ),
        migrations.AddField(
            model_name='client',
            name='materiels_fournis',
            field=models.TextField(blank=True, help_text='Matériels spécifiques fournis par le fournisseur à ce client', null=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
