# Generated by Django 5.2.9 on 2025-12-15 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_used', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('response_tokens', models.IntegerField(default=0)),
                ('duration', models.FloatField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Mois')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du rapport')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('total_interventions', models.IntegerField(default=0, verbose_name='Total interventions')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name="Chiffre d'affaires")),
                ('avg_intervention_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Durée moyenne')),
                ('summary', models.TextField(verbose_name='Résumé exécutif')),
                ('technical_analysis', models.TextField(verbose_name='Analyse technique')),
                ('recommendations', models.TextField(verbose_name='Recommandations')),
                ('equipment_analysis', models.TextField(verbose_name='Analyse des équipements')),
                ('predictive_maintenance', models.TextField(verbose_name='Maintenance prédictive')),
                ('success_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de réussite (%)')),
                ('customer_satisfaction_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Score satisfaction')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
            ],
            options={
                'verbose_name': 'Rapport Mensuel',
                'verbose_name_plural': 'Rapports Mensuels',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(max_length=100, verbose_name='Type de métrique')),
                ('value', models.CharField(max_length=200, verbose_name='Valeur')),
                ('description', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.monthlyreport')),
            ],
        ),
    ]
