# Generated by Django 5.2.9 on 2025-12-16 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('month', models.DateField()),
                ('total_interventions', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('success_rate', models.FloatField(default=0.0)),
                ('customer_satisfaction_score', models.FloatField(default=0.0)),
                ('avg_intervention_duration', models.FloatField(blank=True, null=True)),
                ('summary', models.TextField()),
                ('recommendations', models.TextField()),
                ('technical_analysis', models.TextField()),
                ('predictive_maintenance', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('statistics_data', models.JSONField(blank=True, default=dict)),
                ('ai_raw_response', models.JSONField(blank=True, default=dict)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport IA',
                'verbose_name_plural': 'Rapports IA',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.DeleteModel(
            name='AIRequestLog',
        ),
        migrations.RemoveField(
            model_name='reportmetric',
            name='report',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='ReportMetric',
        ),
    ]
