# Generated by Django 5.2.9 on 2025-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0002_alter_technicien_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='user',
        ),
        migrations.AddField(
            model_name='technicien',
            name='identifiant',
            field=models.CharField(blank=True, help_text='Identifiant pour se connecter', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='technicien',
            name='mot_de_passe',
            field=models.CharField(blank=True, help_text='Mot de passe pour se connecter', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
