# Generated by Django 5.2.9 on 2025-12-05 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0003_remove_technicien_user_technicien_identifiant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicien',
            name='identifiant',
        ),
        migrations.RemoveField(
            model_name='technicien',
            name='mot_de_passe',
        ),
        migrations.AddField(
            model_name='technicien',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Lien avec un utilisateur Django (optionnel pour les techniciens)', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technicien',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
