# Generated by Django 5.2.9 on 2025-12-12 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techniciens', '0004_remove_technicien_identifiant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='technicien',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Lien avec un utilisateur Django', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
